"""Build a simple side-by-side connector clip for modular shelf sockets.

The shelf body generated by component_plan_from_stand_images.py can include
matching rectangular sockets on both sides. This script generates a separate
double-ended bar that fits into two facing sockets, so adjacent shelf columns can
be tied together horizontally.

Usage:
    blender --background --python scripts/blender_build_link_clip.py -- \
        <output.stl> [--gap-mm 2] [--tongue-depth-mm 8] [--length-mm 80] \
        [--height-mm 6] [--clearance-mm 0.3]
"""
from __future__ import annotations

import sys
from pathlib import Path

import bpy


def _argv() -> list[str]:
    return sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []


def _parse_args() -> dict[str, float | str]:
    argv = _argv()
    if not argv:
        print(__doc__)
        sys.exit(1)
    opts: dict[str, float | str] = {
        "output": argv[0],
        "gap_mm": 2.0,
        "tongue_depth_mm": 8.0,
        "length_mm": 80.0,
        "height_mm": 6.0,
        "clearance_mm": 0.3,
    }
    flag_map = {
        "--gap-mm": "gap_mm",
        "--tongue-depth-mm": "tongue_depth_mm",
        "--length-mm": "length_mm",
        "--height-mm": "height_mm",
        "--clearance-mm": "clearance_mm",
    }
    i = 1
    while i < len(argv):
        if argv[i] not in flag_map:
            raise SystemExit(f"unknown option: {argv[i]}")
        opts[flag_map[argv[i]]] = float(argv[i + 1])
        i += 2
    return opts


def _cube(name: str, size: tuple[float, float, float], loc: tuple[float, float, float]) -> bpy.types.Object:
    bpy.ops.mesh.primitive_cube_add(size=1, location=loc)
    obj = bpy.context.object
    obj.name = name
    obj.dimensions = size
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    return obj


def main() -> None:
    opts = _parse_args()
    output = str(opts["output"])
    gap = float(opts["gap_mm"])
    tongue_depth = float(opts["tongue_depth_mm"])
    length = float(opts["length_mm"]) - float(opts["clearance_mm"])
    height = float(opts["height_mm"]) - float(opts["clearance_mm"])
    total_width = (2 * tongue_depth) + gap

    bpy.ops.wm.read_factory_settings(use_empty=True)
    clip = _cube("side_by_side_link_clip", (total_width, length, height), (0, 0, height / 2))

    bevel = clip.modifiers.new(name="softened_edges", type="BEVEL")
    bevel.width = 0.45
    bevel.segments = 2
    bevel.affect = "EDGES"
    bpy.context.view_layer.objects.active = clip
    bpy.ops.object.modifier_apply(modifier=bevel.name)

    bpy.ops.object.select_all(action="DESELECT")
    clip.select_set(True)
    bpy.context.view_layer.objects.active = clip
    Path(output).parent.mkdir(parents=True, exist_ok=True)
    bpy.ops.wm.stl_export(filepath=output, export_selected_objects=True)
    bpy.ops.wm.obj_export(filepath=output.rsplit(".", 1)[0] + ".obj", export_selected_objects=True)
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
