"""
OpenSCAD code generation from height data.

This module generates parametric OpenSCAD code for creating
3D relief models from processed height data.
"""

from datetime import datetime
from typing import Optional

import numpy as np

from image_to_scad.config import ConversionConfig, HeightData
from image_to_scad.exceptions import OpenSCADGenerationError
from image_to_scad.utils.logging import get_logger


class OpenSCADGenerator:
    """
    Generate OpenSCAD code from height data.

    This class creates parametric OpenSCAD code that generates
    3D relief models using the surface() function with height data.

    Example:
        >>> generator = OpenSCADGenerator()
        >>> scad_code = generator.generate(height_data, config)
        >>> print(scad_code)
    """

    def __init__(self) -> None:
        """Initialize the OpenSCAD generator."""
        self._logger = get_logger(__name__)

    def generate(
        self,
        height_data: HeightData,
        config: ConversionConfig,
    ) -> str:
        """
        Generate OpenSCAD code from height data.

        Args:
            height_data: Processed height data from DepthAnalyzer.
            config: Conversion configuration.

        Returns:
            str: Complete OpenSCAD code as a string.

        Raises:
            OpenSCADGenerationError: If code generation fails.
        """
        try:
            # Generate height data file content
            data_content = self._generate_height_data(height_data)

            # Generate OpenSCAD code
            scad_code = self._generate_scad_code(height_data, config, data_content)

            self._logger.debug(
                f"Generated OpenSCAD code: {len(scad_code)} chars, "
                f"resolution: {height_data.resolution}"
            )

            return scad_code

        except Exception as e:
            raise OpenSCADGenerationError(f"Failed to generate OpenSCAD code: {e}") from e

    def _generate_height_data(self, height_data: HeightData) -> str:
        """
        Generate the height data array as OpenSCAD-compatible format.

        Args:
            height_data: Height data to convert.

        Returns:
            str: Height data as embedded array string.
        """
        heights = height_data.heights
        rows, cols = heights.shape

        # Build array rows
        lines = []
        for row_idx in range(rows):
            row_values = ", ".join(f"{v:.3f}" for v in heights[row_idx])
            lines.append(f"    [{row_values}]")

        return "[\n" + ",\n".join(lines) + "\n]"

    def _generate_scad_code(
        self,
        height_data: HeightData,
        config: ConversionConfig,
        data_content: str,
    ) -> str:
        """
        Generate the complete OpenSCAD code.

        Args:
            height_data: Height data.
            config: Conversion configuration.
            data_content: Height data array as string.

        Returns:
            str: Complete OpenSCAD code.
        """
        rows, cols = height_data.resolution
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Calculate cell size
        cell_width = height_data.width_mm / cols
        cell_height = height_data.height_mm / rows

        scad_code = f'''// Generated by image-to-scad
// Date: {timestamp}
// Resolution: {cols} x {rows}
// Dimensions: {height_data.width_mm:.2f} x {height_data.height_mm:.2f} mm

// Configuration Parameters
base_thickness = {config.base_thickness:.2f};  // mm
max_relief_height = {config.max_height:.2f};   // mm
model_width = {height_data.width_mm:.2f};      // mm
model_height = {height_data.height_mm:.2f};    // mm

// Grid Parameters
grid_cols = {cols};
grid_rows = {rows};
cell_width = {cell_width:.4f};   // mm
cell_height = {cell_height:.4f}; // mm

// Height Data
height_data = {data_content};

// Generate Relief Surface
module relief_surface() {{
    for (row = [0 : grid_rows - 2]) {{
        for (col = [0 : grid_cols - 2]) {{
            // Get heights at four corners
            h00 = height_data[row][col];
            h01 = height_data[row][col + 1];
            h10 = height_data[row + 1][col];
            h11 = height_data[row + 1][col + 1];

            // Position
            x = col * cell_width;
            y = row * cell_height;

            // Create two triangles for this cell
            translate([x, y, 0]) {{
                // Triangle 1: bottom-left
                polyhedron(
                    points = [
                        [0, 0, 0],
                        [cell_width, 0, 0],
                        [0, cell_height, 0],
                        [0, 0, h00],
                        [cell_width, 0, h01],
                        [0, cell_height, h10]
                    ],
                    faces = [
                        [0, 1, 2],      // bottom
                        [3, 5, 4],      // top
                        [0, 3, 4, 1],   // front
                        [1, 4, 5, 2],   // right
                        [2, 5, 3, 0]    // left
                    ]
                );

                // Triangle 2: top-right
                polyhedron(
                    points = [
                        [cell_width, 0, 0],
                        [cell_width, cell_height, 0],
                        [0, cell_height, 0],
                        [cell_width, 0, h01],
                        [cell_width, cell_height, h11],
                        [0, cell_height, h10]
                    ],
                    faces = [
                        [0, 1, 2],      // bottom
                        [3, 5, 4],      // top
                        [0, 3, 4, 1],   // front
                        [1, 4, 5, 2],   // right
                        [2, 5, 3, 0]    // left
                    ]
                );
            }}
        }}
    }}
}}

// Main Model
relief_surface();
'''

        return scad_code

    def format_code(self, code: str) -> str:
        """
        Format OpenSCAD code for better readability.

        Args:
            code: OpenSCAD code to format.

        Returns:
            str: Formatted code.
        """
        # Basic formatting - ensure consistent line endings
        lines = code.split("\n")
        formatted_lines = [line.rstrip() for line in lines]
        return "\n".join(formatted_lines)
